AWSTemplateFormatVersion: "2010-09-09"
Region: "us-west-2"
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-02f3f602d23f1659d"
      InstanceType: "t2.micro"
      KeyName: "rony-jenkins"
      IamInstanceProfile: "Ec2_cloudformation_role_Bizops"
